<#
NAME
    Set-SecurityProviders.ps1

SYNOPSIS
    Configures client and server protocols, ciphers, hashes, and key exchanges

SYNTAX
    .\$ScriptName
 
 REFERENCES
    https://docs.microsoft.com/en-us/system-center/scom/plan-security-tls12-config?view=sc-om-2019#configure-windows-to-only-use-tls-12-protocol
    https://docs.microsoft.com/en-US/troubleshoot/windows-server/windows-security/restrict-cryptographic-algorithms-protocols-schannel
#>

# Declare Variables
# -----------------------------------------------------------------------------
$ScriptName = Split-Path $MyInvocation.MyCommand.Path –Leaf
$ScriptDir = Split-Path $MyInvocation.MyCommand.Path –Parent
$DTG = Get-Date -Format yyyyMMddTHHmm
$RootDir = Split-Path $ScriptDir –Parent
$ConfigFile = "$RootDir\config.xml"

Start-Transcript -Path "$RootDir\LOGS\$env:COMPUTERNAME\$ScriptName.log"
Start-Transcript -Path "$env:WINDIR\Temp\$env:COMPUTERNAME-$DTG-$ScriptName.log"

# Load variables from config.xml
If (!(Test-Path -Path $ConfigFile)) {Throw "ERROR: Unable to locate $ConfigFile Exiting..."} 
$XML = ([XML](Get-Content $ConfigFile)).get_DocumentElement()
$WS = ($XML.Component | ? {($_.Name -eq "WindowsServer")}).Settings.Configuration
$InstallShare = ($WS | ? {($_.Name -eq "InstallShare")}).Value
$PkgDir = "$InstallShare\Set-SecurityProviders"

# =============================================================================
# MAIN ROUTINE
# =============================================================================

# Import settings generated by IISCrypto: https://www.nartac.com/Products/IISCrypto/Download
& REG.exe IMPORT "$PkgDir\PCI32.reg"

Stop-Transcript
