resources:
- repo: self

trigger: none # Disable CI build

pr:
  branches:
    include: [ master ]

pool:
  name: GoLion

steps:
- template: azure-pipelines-build-template.yaml
- task: DownloadPackage@1
  displayName: Downloading Pester Module
  inputs:
    feed: GoLion/DasPowershell
    definition: Pester
    version: latest
    downloadPath: 'C:\Program Files\WindowsPowerShell\Modules\Pester'
- powershell: |
    $config = New-PesterConfiguration
    $config.CodeCoverage.Enabled = $true
    $config.Run.Exit = $true
    $config.TestResult.Enabled = $true
    Invoke-Pester -Configuration $config
  displayName: 'Pester Tests'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'testResults.xml'
    failTaskOnFailedTests: true
- task: PublishCodeCOverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: coverage.xml
    pathToSources: $(System.DefaultWorkingDirectory)
    failIfCoverageEmpty: true